#!/usr/bin/env python
# coding: utf-8

# In[1]:


def isPalindrome(str):
  
    # Run loop from 0 to len/2
    for i in range(0, int(len(str)/2)):
        if str[i] != str[len(str)-i-1]:
            return False
    return True
  
# main function
s = "madam"
ans = isPalindrome(s)
  
if (ans):
    print("Yes")
else:
    print("No")


# In[2]:


def isPalindrome(str):
  
    # Run loop from 0 to len/2
    for i in range(0, int(len(str)/2)):
        if str[i] != str[len(str)-i-1]:
            return False
    return True
  
# main function
s = "cycle"
ans = isPalindrome(s)
  
if (ans):
    print("Yes")
else:
    print("No")


# In[3]:


def Remove(duplicate):
final_list = []
for num in duplicate:
if num not in final_list:
final_list.append(num)
return final_list

# Driver Code
duplicate =  [ 5,4,10,20,4,6,10,39,4,39]
print(Remove(duplicate))


# In[ ]:




